Write N-body ICs to a file
exgalsky/mockgen pull request #5
Opened 2024-02-07 20:55 UTC by marcelo-alvarez

Adds the ICs class with a method to write particle positions, masses and velocities, suitable for use in N-body sims. Still under development, will update when ready for review and testing.

2024-02-17 01:47 UTC, marcelo-alvarez commented
@1cosmologist this is ready for you to review (not requesting for you to validate accuracy of the output files).

Running
```
srun -n 16 mockgen mockgen-5 --N 2048 --Niter 1 --laststep writeics --icw --zInit 50
```
on 4 GPU nodes (16 GPUs total) of Perlmutter in the directory
```
/global/cfs/cdirs/mp107d/exgal/users/malvarez/tests/mockgen
```
generates the files
```
/global/cfs/cdirs/mp107d/exgal/users/malvarez/tests/mockgen/output/mockgen-5_13579_Lbox-7700_N-2048_proc[0-15]
```
@jmsexton03 can you have a look and see if these files look ok? If so then we can look at running Nyx on these outside of this issue. They should correspond to the ICs for LCDM cosmology at z=50 in a 7700 Mpc box at 2048^3 resolution, for the following cosmological parameters passed to CAMB:
```
            'T_cmb': 2.72548,
            'h': 0.68,
#=================Omegas========================
            'Omega_m': 0.31,      # Matter density fraction
            'Omega_b': 0.0493890, # baryon density fraction
            'Omega_k': 0.,
#=============Spectral params===================
            'A_s': 2.10058e-9,   # scalar amplitude
            'n_s': 0.96605,      # scalar spectral index
            'alpha_s': 0.,       # scalar spectral running
            'k_pivot': 0.05,     # pivot scale for scalar perturbations
            'r': 0.,             # tensor to scalar ratio
            'n_t': 0.,           # tensor spectral index
            'alpha_t': 0.,       # tensor spectral running
            
#=============reionization========================
            'tau_reion': 0.0543,    # optical depth at reionization
            'YHe': 0.2454,          # Helium fraction
#=============Light relics===========================
            'N_ur': 2.0328,     # Ultra-relativistic species (ultra-light neutrinos)
            'N_ncdm': 1,        # Light massive relics including massive neutrinos
            'm_ncdm': 0.06,     # mass of non-cold light relics
#===========DE EOS===================================
            'w0': -1.,         
            'wa': 0.
```

2024-02-18 23:05 UTC, 1cosmologist commented
@marcelo-alvarez Can you add the details of the Nyx output format. It would be useful to have it documented or linked as a part of this PR.

2024-02-19 00:06 UTC, marcelo-alvarez commented
@1cosmologist sure here is the documentation for Nyx format: https://amrex-astro.github.io/Nyx/docs_html/ICs.html#start-from-a-binary-file

2024-02-21 20:40 UTC, 1cosmologist requested changes
@marcelo-alvarez There seems to be some redundancy with code already implemented in xgfield. I understand not wanting to touch other parts of the pipeline, but for consistent behavior we should not reimplement what already exists, unless absolutely required. Hubble parameter at a certain redshift should be ideally queried from cosmology.

2024-02-21 20:40 UTC, 1cosmologist commented on mockgen/ics.py
> +        H = 100 * h * jnp.sqrt(omegam*(1+z)**3+1-omegam) # flat universe with negligible radiation
We should be doing this from cosmology module...

2024-02-21 20:40 UTC, 1cosmologist commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
These are already implemented in xgfield. Do we need an alternate implementation?

2024-02-23 00:03 UTC, marcelo-alvarez commented on mockgen/ics.py
> +        H = 100 * h * jnp.sqrt(omegam*(1+z)**3+1-omegam) # flat universe with negligible radiation
@1cosmologist thanks. Can you please post the line(s) that would replace `H = 100 ...` above such that it is done from the cosmology module?

2024-02-23 00:12 UTC, marcelo-alvarez commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
@1cosmologist thanks for pointing this out. However, I am not aware of how to do this with the code that is in xgfield. Can you post the lines that should replace
```
qx, qy, qz = ...
x = qx + D * ...
```
above? If this would require changes to xgfield, I suggest we consider how to do the refactor in a separate issue / PR.

2024-02-23 01:09 UTC, 1cosmologist commented on mockgen/ics.py
> +        H = 100 * h * jnp.sqrt(omegam*(1+z)**3+1-omegam) # flat universe with negligible radiation
We would need a simple method in the cosmology module that fetches `Hubble_parameter(z)` from `camb_wsp` (Ref: https://camb.readthedocs.io/en/latest/results.html#camb.results.CAMBdata.hubble_parameter). This should be a simple implementation.

2024-02-23 01:13 UTC, 1cosmologist commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
The comoving grid should use the `comoving_q` function in xgfield https://github.com/exgalsky/xgfield/blob/fcbc1db1c9d8fe29ef3cc77c89e72b09d0d7d6a3/xgfield/libfield.py#L54

The euclidean position similarly should use `euclid_i` from xgfield https://github.com/exgalsky/xgfield/blob/fcbc1db1c9d8fe29ef3cc77c89e72b09d0d7d6a3/xgfield/libfield.py#L69

2024-02-23 01:15 UTC, 1cosmologist commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
I also suggest moving the velocity implementation to xgfield.

2024-02-23 01:29 UTC, marcelo-alvarez commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
@1cosmologist sounds like we have reached a sufficient number of refactoring changes to address this separately. Can we post a new issue on this in mockgen?

2024-02-23 01:32 UTC, marcelo-alvarez commented
See comment inline to review about creatinf a new issue focused on generic interfaces for this functionality.

2024-02-23 01:33 UTC, 1cosmologist commented on mockgen/ics.py
> +        x =  qx + D * self.cube.s1x + b0 * D**2 * self.cube.s2x
I'm not sure we need a new issue here. These codes should not have been a part of writeics in the first place... You can open separate issues in xgfield and cosmology for changes needed there.

2024-02-23 01:35 UTC, 1cosmologist commented
Create new issues in xgfield and cosmology to add velocity and Hubble_parameter methods. But these codes should not be a part of mockgen.

2024-02-23 03:00 UTC, marcelo-alvarez commented
Thanks @1cosmologist for the review. This code needs to be re-written in order to address the issues you raised, so I'm closing this PR without merging. I will not delete the branch in case some of the code in it can be reused in a new implementation.

2024-02-23 03:00 UTC, closed without merging